### ISSUE TITLE
validator#validate_text raises W3CValidators::ValidatorUnavailable

### ISSUE THREAD

**Issue by buren** [w3c-validators/w3c_validators#39]
Caused by the API returning HTTP 400 Bad Request. Calling `#validate_uri` makes a successful request.

```
W3CValidators::ValidatorUnavailable: unable to connect to the validator at https://validator.w3.org/nu/ (response was 400 "Bad request").
from ~/.gem/ruby/2.4.1/gems/w3c_validators-1.3.3/lib/w3c_validators/validator.rb:116:in `rescue in send_request'
from ~/.gem/ruby/2.4.1/gems/w3c_validators-1.3.3/lib/w3c_validators/validator.rb:43:in `send_request'
from ~/.gem/ruby/2.4.1/gems/w3c_validators-1.3.3/lib/w3c_validators/nu_validator.rb:68:in `validate'
from ~/.gem/ruby/2.4.1/gems/w3c_validators-1.3.3/lib/w3c_validators/nu_validator.rb:34:in `validate_uri'
```

**Comment by doc75** [comment]
Could you please provide a sample of code to reproduce your issue ?
If I remember well if you call too many time the service they might blacklist you for a while (not sure if this can explain your issue).

Here is the code I used to test your case, and it works:

```ruby
require 'w3c_validators'

file = '/home/user/ruby/w3c_validators/test/fixtures/valid_html5.html'
validator = ::W3CValidators::NuValidator.new
results = validator.validate_file(file)
puts results.inspect
```

**Comment by doc75** [comment]
@buren any news on this ?
If not, then I'll close this issue as it cannot be reproduced.

**Comment by buren** [comment]
Sorry, I'm not really sure. The api returns 400 for rate limiting, so it could very well have been that.

Thank you.
